kafka:
  bootstrapAddress: ${KAFKA_ADVERTISED_HOST_NAME:kafka}
server:
  port: 8081
elasticsearch:
  host: elastic
  port: 9300
  cluster:
    name: docker-cluster

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
